/* This file was generated by SableCC (http://www.sablecc.org/). */

package lft_2014.compiler_portugol.analysis;

import lft_2014.compiler_portugol.node.*;

public interface Analysis extends Switch
{
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
    void caseTAspa(TAspa node);
    void caseTAte(TAte node);

    void caseTAtribuicao(TAtribuicao node);
    void caseTAvalie(TAvalie node);
    void caseTBlank(TBlank node);
    void caseTBranco(TBranco node);
    void caseTBrancos(TBrancos node);
    void caseTCaractere(TCaractere node);
    void caseTCaso(TCaso node);
    void caseTCmntLn(TCmntLn node);
    void caseTColcDir(TColcDir node);
    void caseTColcEsq(TColcEsq node);
    void caseTComment(TComment node);
    void caseTCommentBody(TCommentBody node);
    void caseTCommentEnd(TCommentEnd node);
    void caseTConst(TConst node);
    void caseTDe(TDe node);
    void caseTDeclaracao(TDeclaracao node);
    void caseTDiferente(TDiferente node);
    void caseTDiv(TDiv node);
    void caseTDoisPontos(TDoisPontos node);
    void caseTE(TE node);
    void caseTEnquanto(TEnquanto node);
    void caseTEntao(TEntao node);
    void caseTEscreva(TEscreva node);
    void caseTFaca(TFaca node);
    void caseTFim(TFim node);
    void caseTFimAvalie(TFimAvalie node);
    void caseTFimEnquanto(TFimEnquanto node);
    void caseTFimPara(TFimPara node);
    void caseTFimSe(TFimSe node);
    void caseTId(TId node);
    void caseTIgual(TIgual node);
    void caseTInicio(TInicio node);
    void caseTInteiro(TInteiro node);
    void caseTLeia(TLeia node);
    void caseTMaiorigl(TMaiorigl node);
    void caseTMaiorq(TMaiorq node);
    void caseTMais(TMais node);
    void caseTMenorigl(TMenorigl node);
    void caseTMenorq(TMenorq node);
    void caseTMenos(TMenos node);
    void caseTMult(TMult node);
    void caseTNao(TNao node);
    void caseTNInt(TNInt node);
    void caseTOu(TOu node);
    void caseTPara(TPara node);
    void caseTParenDir(TParenDir node);
    void caseTParenEsq(TParenEsq node);
    void caseTPasso(TPasso node);
    void caseTPontoVirgula(TPontoVirgula node);
    void caseTPrograma(TPrograma node);
    void caseTReal(TReal node);
    void caseTRepita(TRepita node);
    void caseTSe(TSe node);
    void caseTSenao(TSenao node);
    void caseTSlash(TSlash node);
    void caseTStar(TStar node);
    void caseTTipo(TTipo node);
    void caseTValor(TValor node);
    void caseTVar(TVar node);
    void caseTVirgula(TVirgula node);
    void caseTXor(TXor node);
    Object getIn(Node node);
    Object getOut(Node node);
    void setIn(Node node, Object o);
    void setOut(Node node, Object o);
}
