/* This file was generated by SableCC (http://www.sablecc.org/). */

package lft_2014.compiler_portugol.node;

import lft_2014.compiler_portugol.analysis.*;

@SuppressWarnings("nls")
public final class TCmntLn extends Token
{
    public TCmntLn(String text)
    {
        setText(text);
    }

    public TCmntLn(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCmntLn(this);
    }

    @Override
    public Object clone()
    {
      return new TCmntLn(getText(), getLine(), getPos());
    }
}
