/* This file was generated by SableCC (http://www.sablecc.org/). */

package lft_2014.compiler_portugol.node;

import lft_2014.compiler_portugol.analysis.*;

@SuppressWarnings("nls")
public final class TDe extends Token
{
    public TDe()
    {
        super.setText("de");
    }

    public TDe(int line, int pos)
    {
        super.setText("de");
        setLine(line);
        setPos(pos);
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDe(this);
    }

    @Override
    public Object clone()
    {
      return new TDe(getLine(), getPos());
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDe text.");
    }
}
