/* This file was generated by SableCC (http://www.sablecc.org/). */

package lft_2014.compiler_portugol.node;

import lft_2014.compiler_portugol.analysis.*;

@SuppressWarnings("nls")
public final class TDoisPontos extends Token
{
    public TDoisPontos()
    {
        super.setText(":");
    }

    public TDoisPontos(int line, int pos)
    {
        super.setText(":");
        setLine(line);
        setPos(pos);
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDoisPontos(this);
    }

    @Override
    public Object clone()
    {
      return new TDoisPontos(getLine(), getPos());
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDoisPontos text.");
    }
}
