/* This file was generated by SableCC (http://www.sablecc.org/). */

package lft_2014.compiler_portugol.node;

import lft_2014.compiler_portugol.analysis.*;

@SuppressWarnings("nls")
public final class TFimPara extends Token
{
    public TFimPara()
    {
        super.setText("fimpara");
    }

    public TFimPara(int line, int pos)
    {
        super.setText("fimpara");
        setLine(line);
        setPos(pos);
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFimPara(this);
    }

    @Override
    public Object clone()
    {
      return new TFimPara(getLine(), getPos());
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFimPara text.");
    }
}
