/* This file was generated by SableCC (http://www.sablecc.org/). */

package lft_2014.compiler_portugol.node;

import lft_2014.compiler_portugol.analysis.*;

@SuppressWarnings("nls")
public final class TNInt extends Token
{
    public TNInt(String text)
    {
        setText(text);
    }

    public TNInt(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNInt(this);
    }

    @Override
    public Object clone()
    {
      return new TNInt(getText(), getLine(), getPos());
    }
}
