/* This file was generated by SableCC (http://www.sablecc.org/). */

package lft_2014.compiler_portugol.node;

import lft_2014.compiler_portugol.analysis.*;

@SuppressWarnings("nls")
public final class TPasso extends Token
{
    public TPasso()
    {
        super.setText("passo");
    }

    public TPasso(int line, int pos)
    {
        super.setText("passo");
        setLine(line);
        setPos(pos);
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPasso(this);
    }

    @Override
    public Object clone()
    {
      return new TPasso(getLine(), getPos());
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPasso text.");
    }
}
