/* This file was generated by SableCC (http://www.sablecc.org/). */

package lft_2014.compiler_portugol.node;

import lft_2014.compiler_portugol.analysis.*;

@SuppressWarnings("nls")
public final class TValor extends Token
{
    public TValor()
    {
        super.setText("valor");
    }

    public TValor(int line, int pos)
    {
        super.setText("valor");
        setLine(line);
        setPos(pos);
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTValor(this);
    }

    @Override
    public Object clone()
    {
      return new TValor(getLine(), getPos());
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TValor text.");
    }
}
